import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TaskPilot",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative min-h-screen w-full before:absolute before:content-[''] before:w-96 before:h-80 before:rounded-full before:bg-gradient-radial before:-right-48 before:top-0 before:from-primary/50 before:to-primary before:opacity-20 before:blur-3xl overflow-x-hidden before:-z-10">
          <Navbar />
          <div className="max-w-2xl mx-auto px-6 py-4">{children}</div>
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
